Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/scoring.js
app/views/maneuver_participants/new.haml

JS only attaches to maneuver_participants/new but can attach to others if desired. Warning "are you sure" is triggered when user clicks any links or tries to reload the page with data entered in the form.
@sherson are you happy now

Data loss warning

---

README.md

third of the way to closing #21

add real badge

---

.rubocop.yml
app/controllers/maneuver_participants_controller.rb
app/models/onboard_judging.rb
coverage/.last_run.json
spec/features/recording_maneuver_score_spec.rb

Creating tests for maneuver participants controller

---

coverage/.last_run.json
spec/features/participant_scoreboard_spec.rb

Finished tests for participant scoreboard spec
Addresses #15

Participant Scoreboard Spec

---

coverage/.last_run.json
spec/controller/scoreboard_partial_spec.rb
spec/features/circle_check_score_addition_spec.rb
spec/features/onboard_judging_update_spec.rb
spec/models/distance_target_spec.rb
spec/models/maneuver_participant_spec.rb
spec/models/maneuver_spec.rb
spec/models/participant_spec.rb

Participants model spec

---

Gemfile
Gemfile.lock
app/controllers/maneuver_participants_controller.rb
spec/features/overwriting_maneuver_score_spec.rb

No more URL manipulation

---

Gemfile.lock

Bumped ffi and rack

---

.gitignore
Gemfile
spec/rails_helper.rb
spec/spec_helper.rb
spec/support/current_user.rb

Wanted a few of these configuration values

---

app/views/maneuver_participants/new.haml
app/views/maneuver_participants/show.haml

Hidden fields to make the check_box_tags work

---

coverage/.last_run.json
lib/tasks/reset.rake
spec/rails_helper.rb
spec/support/tasks.rb
spec/tasks/roadeo_reset_spec.rb

This puts the app in a pre-roadeo state, while preserving the maneuversfrom last year. I've done, essentially, this for the last two years when setting up the app.

Added a "reset" task.

---

app/controllers/admin/users_controller.rb
app/controllers/buses_controller.rb
app/controllers/concerns/non_maneuver_score_controller.rb
app/controllers/maneuver_participants_controller.rb
app/controllers/maneuvers_controller.rb
app/views/admin/users/manage.haml
app/views/circle_check_scores/index.haml
app/views/devise/registrations/edit.html.haml
app/views/devise/registrations/new.html.haml
app/views/devise/sessions/new.html.haml
app/views/layouts/application.haml
app/views/maneuver_participants/new.haml
app/views/maneuver_participants/show.haml
app/views/maneuvers/index.haml
app/views/participants/_add_to_queue.haml
app/views/participants/_table.haml
app/views/participants/index.haml
app/views/quiz_scores/index.haml
app/views/shared/_title.haml

Noticed that _most_ pages started with a title of sorts. I pulled that out into the layout/partial. So that that look stays unified.

Created shared "title" partial

---

app/helpers/scoreboard_helper.rb
coverage/.last_run.json

I was looking through some Rails helpers and noticed that I had reinvented the wheel here.

Turns out there's already a helper for this

---

config/initializers/content_security_policy.rb

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

Enable CSP

---

app/assets/stylesheets/application.scss.erb
app/helpers/application_helper.rb
app/views/layouts/application.haml
app/views/participants/welcome.haml
config/application.rb
config/deploy.rb
config/roadeo.yml
coverage/.last_run.json

Closes #72 
Did you know that loading a YAML file and accessing it via a custom property on `Rails.configuration` was built into Rails?
You can also override it anywhere you configure the app; e.g. `config/environments/`

Add app configuration

---

Gemfile.lock
app/helpers/scoreboard_helper.rb
coverage/.last_run.json
spec/helpers/scoreboard_helper_spec.rb

Also beefed up the documentation on these two methods.

Some specs for the more obscure view helpers

---

app/helpers/application_helper.rb
app/models/user.rb
app/views/layouts/_navbar.haml
coverage/.last_run.json
spec/helpers/application_helper_spec.rb

Wrote and tested a helper method for navigation items. Also changed the "are they allowed" logic to use `User#role?`.

Nav cleanup

---

.gitignore
app/controllers/application_controller.rb
app/views/layouts/_navbar.haml
app/views/participants/_participant.haml
app/views/participants/scoreboard.haml
coverage/.last_run.json
lib/scoreboard_renderer.rb
lib/tasks/archive.rake
spec/lib/scoreboard_renderer_spec.rb
spec/tasks/roadeo_archive_spec.rb

Two parts (with specs for each)
1. A utility class for rendering the scordeboard view
2. Rake tasks for writing that view to a file and for getting a copy of compiled assets
Closes #73

Results archive

---

app/assets/javascripts/scoreboard.js

closes #149 
noticed the full screen button didn't work on safari, so I added safari functionality

include safari for full screen usage

---

Capfile
config/deploy/production.rb

Git was the default once upon a time, but depending on that is deprecated.

Install Capistrano Git plugin

---

lib/tasks/archive.rake
spec/support/tasks.rb
spec/tasks/roadeo_archive_spec.rb
spec/tasks/roadeo_reset_spec.rb

Borrowed the fix from [here](https://github.com/rails/sprockets-rails/blob/7137bb169839596b4a84b16173d021de5f988a1e/lib/sprockets/rails/task.rb#L18-L20).
Also rubocopped the file and its spec. Decided to go with a less "magic" way of determining the task name in specs in order to allow both nesting describe blocks **and** context blocks.

Fix production archive task

---

Gemfile
app/controllers/buses_controller.rb
app/controllers/maneuvers_controller.rb
app/models/circle_check_score.rb
app/models/distance_target.rb
app/models/maneuver.rb
app/models/maneuver_participant.rb
app/models/obstacle.rb
app/models/onboard_judging.rb
app/models/quiz_score.rb
app/models/user.rb
db/seeds.rb
spec/lib/scoreboard_renderer_spec.rb
spec/system/signup_page_spec.rb

Looks like there are a few new cops since the last time it was run.

Ran rubocop

---

app/assets/javascripts/channels/circle_check_scores.coffee
app/assets/javascripts/channels/maneuver_participants.coffee
app/assets/javascripts/channels/onboard_judgings.coffee
app/assets/javascripts/channels/participants.coffee
app/assets/javascripts/channels/quiz_scores.coffee
app/assets/javascripts/scoreboard.js
app/assets/stylesheets/scoreboard.scss

closes #102 
It won't animate a second time, if the same cell is updated twice in a row. I'm not entirely sure why but that's also not a very common use case at all, so I'm not super worried about it?

Scoreboard pizazz

---

app/controllers/application_controller.rb

Fix #205, yes there's a typo and yes I did force push to fix it

Change authorization warning to use a `alert` flash type

---

app/controllers/health_controller.rb
config/routes.rb

This is pretty much just a copy of the Rails 7.1 [`Rails::HealthController`](https://api.rubyonrails.org/classes/Rails/HealthController.html).
I'm giving Kamal a try, and it expects to see a `200` at this URL before it declares the container "healthy".

Add health check controller

---

Gemfile
Gemfile.lock

Add gems needed for ed25519 keys

---

Gemfile
Gemfile.lock
app/models/circle_check_score.rb
config/initializers/paper_trail.rb
db/migrate/20240429181500_add_new_json_object_to_versions.rb
db/schema.rb
lib/tasks/versions.rake

Started working on this when I got an error [resetting](https://github.com/umts/umasstransit.rodeo/blob/b2d2237f3e29f22437d4c95d9b3fa49c6444f36d/lib/tasks/reset.rake#L3-L15) the roadeo.
Turns out that the error was actually that I had accidentally loaded a database dump from 2 year ago instead of the one from 1 year ago. But, anyways...

Paper Trail serializer switch

---

spec/spec_helper.rb

Noticed that specs weren't randomized on this app

Randomize spec order

---

.haml-lint.yml
Gemfile
Gemfile.lock

Plenty of offenses, I'll tackle those after.

Add haml_lint
